### ISSUE TITLE
Israeli Supermarkets tracking issue

### ISSUE THREAD

**Issue by yotamN** [osmlab/name-suggestion-index#8236]
This is a tracking issue for all Israeli supermarkets, as I'm not able to add them all in one batch but want to be able to track them and get help from others.

My list is based on existing brands and on Israel Consumer Council. The main thing to note, is that some super brands should be split into more specific brands used by their stores.

- [x] רמי לוי
- [ ] יוחננוף
- [ ] חצי חינם
- [x] שופרסל דיל
- [ ] שופרסל דיל אקסטרה
- [ ] ויקטורי
- [ ] מחסני השוק
- [ ] מחסני השוק בסיטי
- [ ] פוליצר
- [x] יינות ביתן
- [ ] יינות ביתן בסיטי
- [ ] סופר ברקת
- [ ] סאלח דבאח
- [ ] ביתן מרקט בסיטי
- [ ] מחסני השוק בשבילך
- [ ] קשת טעמים
- [ ] קינג סטור
- [ ] סופר
- [ ] זול ובגדול
- [ ] סטופ מרקט
- [ ] מעיין 2000
- [ ] טיב טעם
- [ ] שופרסל שלי
- [ ] פרש מרקט
- [ ] שופרסל אקספרס
- [x] מגה בעיר
- [x] שוק מהדרין
- [ ] אלונית
- [ ] yellow
- [ ] סופר יודה
- [ ] AM:PM

**Comment by Flatroy** [comment]
From this list I added: 
AM:PM,
 שופרסל (אקספרס, דיל, שלי), 
ויקטורי 
טיב טעם

can you update your message?
